apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: project3
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo-statefulset-0.mongo:27017,mongo-statefulset-1.mongo:27017/app?replicaSet=rs0"
  JWT_SECRET_KEY: "supersecretkey12345"
